export default [
  {
    patamar: "Iniciante",
    ND: "1/4",
    bônus_de_ataque: 7,
    dano_médio: 9,
    defesa: 10,
    resistência_forte: 2,
    resistência_média: 0,
    resistência_fraca: -1,
    PV: 4,
    efeito: 12,
  },
  {
    patamar: "Iniciante",
    ND: "1/2",
    bônus_de_ataque: 9,
    dano_médio: 11,
    defesa: 13,
    resistência_forte: 5,
    resistência_média: 3,
    resistência_fraca: 0,
    PV: 6,
    efeito: 13,
  },
  {
    patamar: "Iniciante",
    ND: "1",
    bônus_de_ataque: 11,
    dano_médio: 17,
    defesa: 15,
    resistência_forte: 10,
    resistência_média: 5,
    resistência_fraca: 1,
    PV: 9,
    efeito: 14,
  },
  {
    patamar: "Iniciante",
    ND: "2",
    bônus_de_ataque: 14,
    dano_médio: 21,
    defesa: 18,
    resistência_forte: 12,
    resistência_média: 7,
    resistência_fraca: 3,
    PV: 14,
    efeito: 16,
  },
  {
    patamar: "Iniciante",
    ND: "3",
    bônus_de_ataque: 16,
    dano_médio: 24,
    defesa: 20,
    resistência_forte: 14,
    resistência_média: 9,
    resistência_fraca: 4,
    PV: 21,
    efeito: 17,
  },
  {
    patamar: "Iniciante",
    ND: "4",
    bônus_de_ataque: 17,
    dano_médio: 32,
    defesa: 22,
    resistência_forte: 15,
    resistência_média: 10,
    resistência_fraca: 5,
    PV: 28,
    efeito: 18,
  },
  {
    patamar: "Veterano",
    ND: "5",
    bônus_de_ataque: 20,
    dano_médio: 56,
    defesa: 23,
    resistência_forte: 16,
    resistência_média: 11,
    resistência_fraca: 6,
    PV: 40,
    efeito: 20,
  },
  {
    patamar: "Veterano",
    ND: "6",
    bônus_de_ataque: 24,
    dano_médio: 62,
    defesa: 26,
    resistência_forte: 17,
    resistência_média: 12,
    resistência_fraca: 7,
    PV: 48,
    efeito: 22,
  },
  {
    patamar: "Veterano",
    ND: "7",
    bônus_de_ataque: 26,
    dano_médio: 68,
    defesa: 30,
    resistência_forte: 19,
    resistência_média: 14,
    resistência_fraca: 8,
    PV: 56,
    efeito: 24,
  },
  {
    patamar: "Veterano",
    ND: "8",
    bônus_de_ataque: 27,
    dano_médio: 74,
    defesa: 32,
    resistência_forte: 20,
    resistência_média: 15,
    resistência_fraca: 9,
    PV: 64,
    efeito: 26,
  },
  {
    patamar: "Veterano",
    ND: "9",
    bônus_de_ataque: 29,
    dano_médio: 80,
    defesa: 33,
    resistência_forte: 20,
    resistência_média: 15,
    resistência_fraca: 10,
    PV: 72,
    efeito: 28,
  },
  {
    patamar: "Veterano",
    ND: "10",
    bônus_de_ataque: 34,
    dano_médio: 105,
    defesa: 35,
    resistência_forte: 21,
    resistência_média: 16,
    resistência_fraca: 11,
    PV: 80,
    efeito: 30,
  },
  {
    patamar: "Campeão",
    ND: "11",
    bônus_de_ataque: 36,
    dano_médio: 144,
    defesa: 40,
    resistência_forte: 23,
    resistência_média: 18,
    resistência_fraca: 12,
    PV: 110,
    efeito: 31,
  },
  {
    patamar: "Campeão",
    ND: "12",
    bônus_de_ataque: 37,
    dano_médio: 158,
    defesa: 42,
    resistência_forte: 25,
    resistência_média: 20,
    resistência_fraca: 13,
    PV: 120,
    efeito: 33,
  },
  {
    patamar: "Campeão",
    ND: "13",
    bônus_de_ataque: 39,
    dano_médio: 172,
    defesa: 43,
    resistência_forte: 25,
    resistência_média: 20,
    resistência_fraca: 14,
    PV: 130,
    efeito: 35,
  },
  {
    patamar: "Campeão",
    ND: "14",
    bônus_de_ataque: 43,
    dano_médio: 186,
    defesa: 45,
    resistência_forte: 27,
    resistência_média: 22,
    resistência_fraca: 15,
    PV: 140,
    efeito: 38,
  },
  {
    patamar: "Campeão",
    ND: "15",
    bônus_de_ataque: 46,
    dano_médio: 200,
    defesa: 49,
    resistência_forte: 27,
    resistência_média: 22,
    resistência_fraca: 16,
    PV: 150,
    efeito: 40,
  },
  {
    patamar: "Campeão",
    ND: "16",
    bônus_de_ataque: 47,
    dano_médio: 235,
    defesa: 52,
    resistência_forte: 29,
    resistência_média: 24,
    resistência_fraca: 17,
    PV: 160,
    efeito: 42,
  },
  {
    patamar: "Lenda",
    ND: "17",
    bônus_de_ataque: 49,
    dano_médio: 288,
    defesa: 53,
    resistência_forte: 29,
    resistência_média: 24,
    resistência_fraca: 18,
    PV: 204,
    efeito: 44,
  },
  {
    patamar: "Lenda",
    ND: "18",
    bônus_de_ataque: 52,
    dano_médio: 306,
    defesa: 55,
    resistência_forte: 31,
    resistência_média: 26,
    resistência_fraca: 19,
    PV: 216,
    efeito: 47,
  },
  {
    patamar: "Lenda",
    ND: "19",
    bônus_de_ataque: 54,
    dano_médio: 324,
    defesa: 58,
    resistência_forte: 31,
    resistência_média: 26,
    resistência_fraca: 20,
    PV: 228,
    efeito: 47,
  },
  {
    patamar: "Lenda",
    ND: "20",
    bônus_de_ataque: 56,
    dano_médio: 344,
    defesa: 60,
    resistência_forte: 33,
    resistência_média: 28,
    resistência_fraca: 21,
    PV: 240,
    efeito: 49,
  },
  {
    patamar: "L+",
    ND: "S",
    bônus_de_ataque: 60,
    dano_médio: 485,
    defesa: 64,
    resistência_forte: 35,
    resistência_média: 30,
    resistência_fraca: 23,
    PV: 500,
    efeito: 51,
  },
  {
    patamar: "S+",
    ND: "S+",
    bônus_de_ataque: 67,
    dano_médio: 540,
    defesa: 59,
    resistência_forte: 37,
    resistência_média: 33,
    resistência_fraca: 26,
    PV: 800,
    efeito: 55,
  },
];
