import { SavingThrows } from "../types/sheet";

interface useGrimoireSheetProps {
  nd: string;
  attacks: {
    type: "melee" | "range";
    damage: string;
  }[];
  charisma: number;
  constitution: number;
  dexterity: number;
  intelligence: number;
  strength: number;
  wisdom: number;
  statistic: {
    PV: number;
    defesa: number;
    bônus_de_ataque: number;
    dano_médio: number;
    weak: number;
    medium: number;
    strong: number;
  };
  getDamageRoll: (
    averageDamage: number | undefined,
    attackDamage: string,
  ) => string;
  getSavingThrowValue: (savingThrow: SavingThrows) => number;
}

export const useGrimoireSheet = ({
  nd,
  attacks,
  charisma,
  constitution,
  dexterity,
  intelligence,
  strength,
  wisdom,
  statistic,
  getDamageRoll,
  getSavingThrowValue,
}: useGrimoireSheetProps) => {
  return {
    isJDA: true,
    playername: "",
    trace: "",
    torigin: "",
    tlevel: "",
    charnivel: nd,
    for: strength,
    des: dexterity,
    con: constitution,
    int: intelligence,
    sab: wisdom,
    car: charisma,
    vidatotal: statistic.PV,
    vida: statistic.PV,
    vidatemp: "0",
    manatotal: "0",
    mana: "0",
    manatemp: "0",
    defesaatributo: "0",
    defesaoutros: statistic.defesa - 10,
    proficiencias: "",
    charnotes: "",
    ts: "0",
    to: "0",
    oficionome: "",
    oficio2nome: "",
    divindade: "",
    modatributodefesa: "",
    tamanho: "0",
    deslocamento: "9m (6q)",
    cdatributo: "@{int_mod} + @{condicaopermental}",
    cdequips: "0",
    cdpoderes: "0",
    cdoutros: "0",
    extraslot: "0",
    rolltemp: "0",
    ataquetemp: "0",
    periciatemp: "0",
    resistemp: "0",
    danotemp: "0",
    fortemp: "0",
    destemp: "0",
    contemp: "0",
    inttemp: "0",
    sabtemp: "0",
    cartemp: "0",
    abalado: "0",
    agarrado: "0",
    alquebrado: "0",
    apavorado: "0",
    atordoado: "0",
    caido: "0",
    cego: "0",
    confuso: "0",
    debilitado: "0",
    desprevenido: "0",
    doente: "0",
    emchama: "0",
    enfeiticado: "0",
    enjoado: "0",
    enreado: "0",
    envenenado: "0",
    esmorecido: "0",
    exausto: "0",
    fascinado: "0",
    fatigado: "0",
    fraco: "0",
    frustrado: "0",
    imovel: "0",
    inconsciente: "0",
    indefeso: "0",
    lento: "0",
    ofuscado: "0",
    paralizado: "0",
    pasmo: "0",
    petrificacao: "0",
    sangrando: "0",
    surdo: "0",
    surpreendido: "0",
    vulneravel: "0",
    acrobacia_treinada: "0",
    acrobaciaatributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    acrobaciaoutros: "0",
    adestramento_treinada: "0",
    adestramentoatributo2: "@{car_mod} + @{condicaopermental}",
    adestramentooutros: "0",
    atletismo_treinada: "0",
    atletismoatributo2: "@{for_mod} + @{condicaoperfisico} + @{condicaocego}",
    atletismooutros: "0",
    atuacao_treinada: "0",
    atuacaoatributo2: "@{car_mod} + @{condicaopermental}",
    atuacaooutros: "0",
    cavalgar_treinada: "0",
    cavalgaratributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    cavalgaroutros: "0",
    conhecimento_treinada: "0",
    conhecimentoatributo2: "@{int_mod} + @{condicaopermental}",
    conhecimentooutros: "0",
    cura_treinada: "0",
    curaatributo2: "@{sab_mod} + @{condicaopermental}",
    curaoutros: "0",
    diplomacia_treinada: "0",
    diplomaciaatributo2: "@{car_mod} + @{condicaopermental}",
    diplomaciaoutros: "0",
    enganacao_treinada: "0",
    enganacaoatributo2: "@{car_mod} + @{condicaopermental}",
    enganacaooutros: "0",
    fortitude_treinada: "0",
    fortitudeatributo2: "@{con_mod} + @{condicaoperfisico}",
    fortitudeoutros: getSavingThrowValue("fortitude") - constitution,
    furtividade_treinada: "0",
    furtividadeatributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    furtividadeoutros: "0",
    guerra_treinada: "0",
    guerraatributo2: "@{int_mod} + @{condicaopermental}",
    guerraoutros: "0",
    iniciativa_treinada: "0",
    iniciativaatributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    iniciativaoutros: "0",
    intimidacao_treinada: "0",
    intimidacaoatributo2: "@{car_mod} + @{condicaopermental}",
    intimidacaooutros: "0",
    intuicao_treinada: "0",
    intuicaoatributo2: "@{sab_mod} + @{condicaopermental}",
    intuicaooutros: "0",
    investigacao_treinada: "0",
    investigacaoatributo2: "@{int_mod} + @{condicaopermental}",
    investigacaooutros: "0",
    jogatina_treinada: "0",
    jogatinaatributo2: "@{car_mod} + @{condicaopermental}",
    jogatinaoutros: "0",
    ladinagem_treinada: "0",
    ladinagematributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    ladinagemoutros: "0",
    luta_treinada: "0",
    lutaatributo2: "@{for_mod} + @{condicaoperfisico} + @{condicaocego}",
    lutaoutros: statistic.bônus_de_ataque - strength,
    misticismo_treinada: "0",
    misticismoatributo2: "@{int_mod} + @{condicaopermental}",
    misticismooutros: "0",
    nobreza_treinada: "0",
    nobrezaatributo2: "@{int_mod} + @{condicaopermental}",
    nobrezaoutros: "0",
    oficio_treinada: "0",
    oficioatributo2: "@{int_mod} + @{condicaopermental}",
    oficiooutros: "0",
    oficio2_treinada: "0",
    oficio2atributo2: "@{int_mod} + @{condicaopermental}",
    oficio2outros: "0",
    percepcao_treinada: "0",
    percepcaoatributo2: "@{sab_mod} + @{condicaopermental}",
    percepcaooutros: "0",
    pilotagem_treinada: "0",
    pilotagematributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    pilotagemoutros: "0",
    pontaria_treinada: "0",
    pontariaatributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    pontariaoutros: "0",
    reflexos_treinada: "0",
    reflexosatributo2: "@{des_mod} + @{condicaoperfisico} + @{condicaocego}",
    reflexosoutros: getSavingThrowValue("reflex") - dexterity,
    religiao_treinada: "0",
    religiaoatributo2: "@{sab_mod} + @{condicaopermental}",
    religiaooutros: "0",
    sobrevivencia_treinada: "0",
    sobrevivenciaatributo2: "@{sab_mod} + @{condicaopermental}",
    sobrevivenciaoutros: "0",
    vontade_treinada: "0",
    vontadeatributo2: "@{sab_mod} + @{condicaopermental}",
    vontadeoutros: getSavingThrowValue("will") - wisdom,
    attacks: attacks.map((attack) => ({
      nomeataque: attack.type === "melee" ? "Corpo a Corpo" : "Distância",
      danoataque: attack.damage,
      danocriticoataque: `${attack.damage} + ${attack.damage}`, //TODO: maybe add strength
      danoextraataque: getDamageRoll(statistic.dano_médio, attack.damage)
        .split("+")[1]
        .trim(),
      margemcriticoataque: "19",
      bonusataque: "0",
      dadoextraataque: "0",
      multiplicadorcriticoataque: "2",
      ataquedescricao: "",
      ataquepericia:
        attack.type === "melee"
          ? "@{lutatotal}+@{condicaomodataquecc}+@{condicaomodataque}"
          : "@{pontariatotal}+@{condicaomodataquecc}+@{condicaomodataque}",
      ataquetipodedano: "",
      ataquealcance: attack.type === "melee" ? "Corpo a Corpo" : "Médio",
      modatributodano: "@{for_mod}",
      tipocritico: "",
    })),
  };
};
